# This is a basic workflow to help you get started with Actions

name: Testing workflow variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greegting_job:
    runs-on: ubuntu-latest
    env: 
      Greeting: Hello

    steps:
      - name: "hello it's Monday"
        run: echo "$Greeting $first_name is using $cloud"
        env:
          first_name: Swati
 
